# Model
device: 0

name: facebook/opt-125m
model_name: blip2
model_class: Blip2OPT
small_name: facebook/opt-125m
tokenizer_class: GPT2Tokenizer
tokenizer_name: facebook/opt-125m
cls_name: distilbert-base-cased 
cls_class: AutoModel 
inner_params: []
# - opt_model.model.decoder.layers.29.fc1.weight
# - opt_model.model.decoder.layers.29.fc2.weight
# - opt_model.model.decoder.layers.30.fc1.weight
# - opt_model.model.decoder.layers.30.fc2.weight
# - opt_model.model.decoder.layers.31.fc1.weight
# - opt_model.model.decoder.layers.31.fc2.weight

# Method
alg: CoRE_MULTI
alg_name: CoRE_MULTI
lr: 1e-5
edit_lr: 1e-2
seed: 0
lr_lr: 0.0
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
final_eval: True
supervised: False
train_base: False
no_grad_layers: null
soft_weighting: False
checkpoint_grad: False
cross_attend: False
cos: False
freeze: null
square: True
bound_embeds: False
use_all_negatives: False
freeze_cntr: False
dist_heads: 1
lora: null
archive: results/models/CoRE_MULTI/blip2-caption

batch_size: 1
model_save_pt: 1000
edit_bs: 1
silent: False
#max_epochs: 1
max_iters: 50000
log_interval: 200
val_interval: 5000
early_stop_patience: 30000
early_stop_key: "loss/total_edit_val"
eval_only: True
half: False
save: False
debug: False
log_errors: False
unlikelihood: True


val_batch_size: 1
accumulate_bs: 1
val_steps: 1000
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results

# Multimodal
exact_match: False
qformer_checkpoint: /kilab/hf_cache/blip2_pretrained_flant5xxl.pth
qformer_name_or_path: google-bert/bert-base-uncased
state_dict_file: /kilab/hf_cache/eva_vit_g.pth

# image
core_image: /kilab/data/editing-data/CoRE/